### ISSUE TITLE
Support for summary metric type

### ISSUE THREAD

**Issue by grantwest** [beam-telemetry/telemetry_metrics_prometheus#41]
Is there a technical reason summary is unsupported? It is the default summary type generated in phoenix projects. This is something I would be interesting in working on, but I thought I would ask before I spent time looking at it.

**Comment by bryannaegele** [comment]
It's discussed at length in https://github.com/beam-telemetry/telemetry_metrics_prometheus_core/issues/11. Things have changed in the 2 years since it was last discussed.

Opentelemetry metrics will be completed relatively soon and I'd recommend switching when that happens. Rewriting a large chunk of the core library just isn't worth the effort imo.

**Comment by grantwest** [comment]
There a lot of packages with similar names/functions and I haven't mastered it yet. When you say "opentelemetry metrics will be completed relatively soon" which package do you mean?

**Comment by bryannaegele** [comment]
https://hex.pm/packages/opentelemetry_api
